/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LanAnh' at '11/13/16 11:32 AM' with Gradle 3.1
 *
 * @author LanAnh, @date 11/13/16 11:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
